### ISSUE TITLE
I think there should be a full screen feature or at least better screen size, as it's frustrating playing a game when you can't see al of it

### ISSUE THREAD

**Issue by CorrnLorrd** [Cattn/msgweb#1]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Cattn** [comment]
A planned feature, thanks for sugg4estion, it'll be like a expand button that'll let you make the game much bigger

**Comment by Cattn** [comment]
I'll leave this open until it's added

**Comment by Cattn** [comment]
Done in https://github.com/Cattn/msgweb/commit/f6dc9c434fda3feabb5b51d1b6ac751c9b04ba67
