### ISSUE TITLE
Proxy Unblocker

### ISSUE THREAD

**Issue by Ishan877** [Cattn/msgweb#11]
I'd basically like to have a proxy which unblocks every website on google search. Some alternatives are nimbuss.cloud, gointerstellar.app. That's basically it. Since there's already a TON of unblocked gaming websites on school.

**Comment by Cattn** [comment]
You can check out https://noctura.tech/ which is a project in which I was a part of the dev team, but other than that we don't offer any proxies (yet, may change)
