### ISSUE TITLE
Site!

### ISSUE THREAD

**Issue by TrickJoker312** [Cattn/msgweb#2]
So... what's the site?

**Comment by Cattn** [comment]
https://cattn.github.io/msgweb/

**Comment by TrickJoker312** [comment]
Ok, thank you! I appreciate it!

**Comment by Cattn** [comment]
No problem! We have more links you can find in discord.gg/mathstudy 

Also if you feel like your issue is resolved could you close this?

**Comment by TrickJoker312** [comment]
Okay!
