### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by ginger12764** [Cattn/msgweb#7]
**Describe the bug**
It will not let me play among us

**To Reproduce**
4. See the error

**Expected behavior**
I expected to be able to play the game

**Screenshots**
![image](https://user-images.githubusercontent.com/123848269/228878170-880934c5-c762-4ba8-9508-ce9488a8eeb4.png)

**Windows Or Chromebook?**
Chromebook
**Additional context**
No

**Comment by Cattn** [comment]
Yeah, that game is broken I will remove it in the next update
