### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by PHYT90DitYT** [Cattn/msgweb#8]
**Describe the bug**
There is no Package.json, therefore I cannot deploy it to Cyclic.sh.

**Expected behavior**
Expected to connect cyclic.
**Screenshots**
![image](https://github.com/Cattn/msgweb/assets/136361545/d67a44d3-3786-4f67-9e40-c3605499f3ec)
**Windows Or Chromebook?**
Chromebook.
**Additional context**
Nothing, Just installed cyclic.

**Comment by Nailington** [comment]
We don't actually need one, as we have no Node Modules in our project.... I will put this on a side burner to remember to generate one when I load up VSCode next. Feel free to ping me in our discord server to remind me to do so lol.

**Comment by PHYT90DitYT** [comment]
k, thanks.
